import pandas as pd, os, glob

configfile: "config.yaml"

RESULTS   = config["results_dir"]
LOGS      = config["logs_dir"]
THREADS   = config.get("threads", 4)
THREADS_H = config.get("threads_heavy", THREADS)
GENOMES_DIR = config["input"]["genomes_dir"]
FAA_DIR     = config["input"]["faa_dir"]
CONTAINERS  = config.get("containers", {})

GENOMES = [os.path.splitext(os.path.basename(f))[0]
           for f in glob.glob(os.path.join(GENOMES_DIR, "*.fasta")) +
                    glob.glob(os.path.join(GENOMES_DIR, "*.fna"))]

for smk in ["orthofinder", "cactus", "phylogeny", "functional", "aggregate"]:
    include: os.path.expanduser(f"~/lab/pipelines/pangenome_eukaryote/rules/{smk}.smk")

rule all:
    input:
        os.path.join(RESULTS, "orthofinder/Results/SpeciesTree_rooted.txt"),
        os.path.join(RESULTS, "tables/pav_matrix.csv"),
        os.path.join(RESULTS, "tables/functional_table.csv"),
        os.path.join(RESULTS, "metrics_summary.xlsx"),
